// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxHhiEIfu_43PjNxTz9RY2yjq7fGnnNhY',
    appId: '1:30077375601:web:99e79b8bf38244421df7d0',
    messagingSenderId: '30077375601',
    projectId: 'it-project-22ec0',
    authDomain: 'it-project-22ec0.firebaseapp.com',
    databaseURL: 'https://it-project-22ec0-default-rtdb.firebaseio.com',
    storageBucket: 'it-project-22ec0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDku8iDeeQuZd35ElAnLyYdBBJsYoBBz_0',
    appId: '1:30077375601:android:833730b89e65ddea1df7d0',
    messagingSenderId: '30077375601',
    projectId: 'it-project-22ec0',
    databaseURL: 'https://it-project-22ec0-default-rtdb.firebaseio.com',
    storageBucket: 'it-project-22ec0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX_g8O-PU8OtHSJK7vN9DoOyYD17u8GA8',
    appId: '1:30077375601:ios:69f177940641c7941df7d0',
    messagingSenderId: '30077375601',
    projectId: 'it-project-22ec0',
    databaseURL: 'https://it-project-22ec0-default-rtdb.firebaseio.com',
    storageBucket: 'it-project-22ec0.appspot.com',
    iosBundleId: 'com.example.itApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX_g8O-PU8OtHSJK7vN9DoOyYD17u8GA8',
    appId: '1:30077375601:ios:237768002b1758521df7d0',
    messagingSenderId: '30077375601',
    projectId: 'it-project-22ec0',
    databaseURL: 'https://it-project-22ec0-default-rtdb.firebaseio.com',
    storageBucket: 'it-project-22ec0.appspot.com',
    iosBundleId: 'com.example.itApplication.RunnerTests',
  );
}
